name: Build with Maven OAuth

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Setup Java and Maven (required prerequisite)
      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      # Setup Maven with OAuth token
      - name: Setup Maven with OAuth
        id: setup-maven-oauth
        uses: curityio/curity-maven-gh-action@v1
        with:
          client-secret: ${{ secrets.CURITY_CLI_CLIENT_SECRET }}
          
      - name: Publish package
        run: mvn deploy ${{ steps.setup-maven-oauth.outputs.maven-deploy-args }}
